### ISSUE TITLE
Systemd timer  - service failed

### ISSUE THREAD

**Issue by ixzh** [thevinter/styli.sh#16]
```
× stylish.service - stylish wallpaper
     Loaded: loaded (/etc/systemd/system/stylish.service; static)
     Active: failed (Result: exit-code) since Sun 2021-06-06 14:17:27 +08; 25s ago
TriggeredBy: ● stylish.timer
    Process: 5066 ExecStart=/home/bo/Downloads/styli.sh/styli.sh -p (code=exited, status=1/FAILURE)
   Main PID: 5066 (code=exited, status=1/FAILURE)
        CPU: 239ms

Jun 06 14:17:27 nana styli.sh[5071]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
Jun 06 14:17:27 nana styli.sh[5071]:   File "/usr/lib/python3.9/site-packages/pywal/__init__.py", line 12, in <module>
Jun 06 14:17:27 nana styli.sh[5071]:     from .settings import __version__, __cache_version__
Jun 06 14:17:27 nana styli.sh[5071]:   File "/usr/lib/python3.9/site-packages/pywal/settings.py", line 21, in <module>
Jun 06 14:17:27 nana styli.sh[5071]:     CACHE_DIR = os.getenv("PYWAL_CACHE_DIR", os.path.join(HOME, ".cache", "wal"))
Jun 06 14:17:27 nana styli.sh[5071]:   File "/usr/lib/python3.9/posixpath.py", line 76, in join
Jun 06 14:17:27 nana styli.sh[5071]:     a = os.fspath(a)
Jun 06 14:17:27 nana styli.sh[5071]: TypeError: expected str, bytes or os.PathLike object, not NoneType
Jun 06 14:17:27 nana systemd[1]: stylish.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by thevinter** [comment]
Can you provide more details on when this is happening? By just running ```styli.sh -p``` I get no errors. Are you using any Desktop Environment?

**Comment by ixzh** [comment]
> Can you provide more details on when this is happening?

Hi, I'm using Arch+xmonad
Basically I want to change wallpaper every 10 mins.

So I added test.service and test.timer under /etc/systemd/system/ and enable the service. below is the test.service file content:

```
[Unit]
 Description=stylish wallpaper

 [Service]
 Type=simple
 ExecStart=/home/bo/Downloads/styli.sh/  styli.sh -p -s pea
``` 
which gave the above error. 

Could it be the HOME variable not bound to any file path when running from service from above location, as suggested by the error info?

**Comment by thevinter** [comment]
I assume it's an issue on pywal's end. Their script probably doesn't expect `wal` to be ran as root so it throws an error. 
Try pytting the service in `~/.config/systemd/user` and start it from there

Relevant wiki: https://wiki.archlinux.org/title/Systemd/User

**Comment by ixzh** [comment]
> Try pytting the service in `~/.config/systemd/user` and start it from there

it works.Closed with thanks!!!
