### ISSUE TITLE
Help with reddit API

### ISSUE THREAD

**Issue by HarshaVardhanNakkina** [thevinter/styli.sh#24]
I am trying to create a similar app for windows using Go language called [go-wallpaper](https://github.com/HarshaVardhanNakkina/go-wallpaper).
I am trying to download images from subreddits just like styli.sh does, but I am getting a `429 Too Many Requests` error
I tried different user agents in the header, but it is not working
How to get around this?

**Comment by thevinter** [comment]
Sorry for the late answer. It looks like you solved it by yourself but if not feel free to reopen the issue. Congratulations on your project :)
