### ISSUE TITLE
Black screen on multiple displays KDE

### ISSUE THREAD

**Issue by Casul51** [thevinter/styli.sh#35]
Basically KDE can't find file when tries to set a wallpaper for multiple displays (probably 3+), so 1 display have wallpaper others have black screen. Fix for this:
style.sh line 349     (i'm bad at pull requests xd)
`rm "${cachedir}/tmp.jpg"`
 to   
`sleep 5 && rm "${cachedir}/tmp.jpg" `

**Comment by thevinter** [comment]
Fixed in [https://github.com/thevinter/styli.sh/commit/232f23ccb0dc9701372bc8aafd5b67399917c51e](232f23c). Thanks!
