### ISSUE TITLE
source.unsplash.com is unavailable

### ISSUE THREAD

**Issue by akhiljalagam** [thevinter/styli.sh#36]
it seems like source.unsplash.com is discontinued. this should be updated to new available url format of unspalsh.

**Comment by akhiljalagam** [comment]
✅ I am using this **new api URL** with access_key to get random wallpaper.

```
link=$(curl 'https://api.unsplash.com/photos/random/?client_id=<use-your-access-key>&query=nature&orientation=landscape&w=3840&h=2160' | jq -r .urls.raw)
wget -q -O ~/.cache/wallpaper.jpg $link
feh --no-fehbg --bg-fill ~/.cache/wallpaper.jpg
```

**Comment by thevinter** [comment]
Thanks, I will look into it as soon as possible

**Comment by thevinter** [comment]
Do you have any info about it being discontinued? To me it looks like they just didn't update their SSL certificate

**Comment by akhiljalagam** [comment]
> Do you have any info about it being discontinued? To me it looks like they just didn't update their SSL certificate

I think I have mistaken. It's just an SSL certificate issue. thanks.

**Comment by thevinter** [comment]
No worries. I'll put the issue on hold hoping it will get fixed in the following days. If not i'll figure a way to use the API, thanks.

**Comment by thevinter** [comment]
Unsplash renewed their certificate so everything's working now :partying_face:
