### ISSUE TITLE
Bug with Ubuntu 22.04 + gnome 42 if darkmode enabled

### ISSUE THREAD

**Issue by Camiyo** [thevinter/styli.sh#41]
Hello,
Stylish was not working on my Ubuntu 22.04 + GNOME 42 and Darkmode enabled.

There are now 2 ways to configure a new wallpaper with gsettings:

To set the wallpaper of the light mode:
```bash
gsettings set org.gnome.desktop.background picture-uri ''
```
To set the wallpaper of the dark mode:
```bash
gsettings set org.gnome.desktop.background picture-uri-dark ''
```

As workaround in styli.sh I've made this change : 
```bash
371 gnome_cmd() {
372     #gsettings set org.gnome.desktop.background picture-uri "file://${wallpaper}"
373     gsettings set org.gnome.desktop.background picture-uri-dark "file://${wallpaper}"
374 }
```

Camille.

**Comment by thevinter** [comment]
Thanks! As I'm not familiar with GNOME would leaving both strings cause side effects? Or would it just change the wallpaper for both light and dark mode? Thanks

**Comment by Camiyo** [comment]
No you could keep both strings, it seems ok.

**Comment by thevinter** [comment]
Thanks, fixed

https://github.com/thevinter/styli.sh/commit/c708b175b83f2ccd8c6de4a20e819cea97a1558f #
