### ISSUE TITLE
Disabling styli.sh when using Vim

### ISSUE THREAD

**Issue by blogdemoi** [thevinter/styli.sh#43]
Hi,

Is it possible to disable styli.sh when I am using Vim? When I use Vim I also use the Limelight plugin https://github.com/junegunn/limelight.vim and it seems it cannot calculate the color for dimming down the surrounding paragraphs.

Thank you.

**Comment by thevinter** [comment]
Hi, I think that the issue here is not with styli.sh but with [pywal](https://github.com/dylanaraps/pywal) or with your terminal emulator. You should probably open the issue on their end :)
