### ISSUE TITLE
script runs without problem but wallpaper is not changed (manjaro gnome)

### ISSUE THREAD

**Issue by Yalchin403** [thevinter/styli.sh#7]

**Comment by thevinter** [comment]
GNOME is currently not supported as it overrides feh automatically. See [[Issue#255]](https://github.com/derf/feh/issues/225)

I'll see what I can do

**Comment by thevinter** [comment]
As a temporary fix you can replace the lines from 118 to 123 inclusive with just:
`gsettings set org.gnome.desktop.background picture-uri file://$PWD/wallpaper`

It will work with the unsplash (not with the reddit flag).

**Comment by Nenoeldeeb** [comment]
> As a temporary fix you can replace the lines 134 and 151 with just:
> `gsettings set org.gnome.desktop.background picture-uri file://$PWD/wallpaper.jpg`
> 
> It should work, but not having GNOME I can't test it at the moment.

Is it also valid for cinnamon?

**Comment by thevinter** [comment]
It is valid for cinnamon with just a slight tweak 
```gsettings set org.cinnamon.desktop.background picture-uri  "file://$PWD/wallpaper.jpg"```

Native support for cinnamon is coming soon. GNOME is now supported thanks to PR #15.
