### ISSUE TITLE
unable to use multiple search keywords

### ISSUE THREAD

**Issue by PeisongXiao** [thevinter/styli.sh#8]
I want to be able to search for a phrase instead of just a single word when I'm using the `-s` option.
I tempered with the script because when I put quotes on my phrase it outputs something like `styli.sh: line 113: [: xxx: binary operator expected`. I changed line 113 to `if [ ! -z "$search" ]` but that didn't seem to work much more than remove the warning.

**Comment by thevinter** [comment]
The issue should now be solved. 

`$ styli.sh -s "snow sea"` will work.
